import type { ComponentChildren } from "preact";
import { useLayoutEffect, useRef } from "preact/hooks";
import { day } from "../domain/format";
import { useReport } from "./context";

/** A footer link: always to a fixed lockrot address, never to anything from the document. */
function Lnk({ href, children }: { href: string; children: ComponentChildren }) {
  return (
    <a className="lnk" href={href} target="_blank" rel="noopener noreferrer">
      {children}
    </a>
  );
}

/**
 * Publishes the footer's rendered height as `--footer-h`, the same discipline `Header.tsx#useHeaderHeight`
 * keeps for `--topbar-h`. `.shell`'s sticky rail and detail column (`ui/app.css`) need it: the footer
 * renders straight after `.shell` with nothing sized to hold it away, so the page's true maximum scroll
 * always leaves exactly `--footer-h` of the footer standing between a stuck panel's lowest reachable
 * point and the viewport's own bottom edge, whatever `.shell`'s own row height happens to be (DESIGN.md
 * §8, PD-DETAIL-5). Set through the CSSOM, which the page's CSP allows (DESIGN.md §1.3).
 */
function useFooterHeight() {
  const ref = useRef<HTMLElement>(null);

  useLayoutEffect(() => {
    const node = ref.current;
    if (node === null || typeof ResizeObserver === "undefined") return undefined;
    const root = document.documentElement;
    const observer = new ResizeObserver(() => {
      root.style.setProperty("--footer-h", `${Math.ceil(node.getBoundingClientRect().height)}px`);
    });
    observer.observe(node);
    // The sticky columns give up the footer's height only while the footer is on screen: sized
    // against it all the time, a short viewport (a laptop at 125% zoom, devtools open) left them a
    // sliver for the whole page to protect the last screenful of it (DESIGN.md §8, PD-DETAIL-5).
    const visible =
      typeof IntersectionObserver === "undefined"
        ? null
        : new IntersectionObserver(([entry]) => {
            root.classList.toggle("footer-in-view", entry?.isIntersecting === true);
          });
    visible?.observe(node);

    return () => {
      observer.disconnect();
      visible?.disconnect();
      root.style.removeProperty("--footer-h");
      root.classList.remove("footer-in-view");
    };
  }, []);

  return ref;
}

/**
 * The colophon: who made the instrument, not who was audited (legacy report.html:94-120). A report
 * is usually read by someone who did not run it, so the page says how to get the same page for
 * their own lock instead of leaving them to work it out from a link to the documentation.
 */
export function Footer({ inert = false }: { inert?: boolean }) {
  const { model } = useReport();
  const version = model.report.tool.version ?? "—";
  const ref = useFooterHeight();

  return (
    <footer className="colophon" ref={ref} inert={inert}>
      <p>
        Generated by lockrot <span className="mono">{version}</span> on{" "}
        <span className="mono">{day(model.report.generatedAt)}</span>. Everything it shows is inside this
        file; nothing in it loads from the network.
      </p>
      <p className="cta">
        Run it on your own <span className="mono">composer.lock</span>:{" "}
        <code>composer require --dev somework/lockrot</code>, then{" "}
        <code>composer lockrot --format=html &gt; report.html</code>. No Composer plugin wanted? The{" "}
        <Lnk href="https://lockrot.dev/lockrot.phar">PHAR</Lnk> needs nothing installed.
      </p>
      <p>
        <Lnk href="https://github.com/somework/lockrot">Source</Lnk> &middot;{" "}
        <Lnk href="https://packagist.org/packages/somework/lockrot">somework/lockrot</Lnk> &middot;{" "}
        <Lnk href="https://lockrot.dev/">Documentation</Lnk> &middot;{" "}
        <Lnk href="https://github.com/somework/lockrot/issues">Report a wrong verdict</Lnk>
      </p>
      <p>
        Written by <Lnk href="https://github.com/somework">Igor Pinchuk</Lnk> (
        <Lnk href="https://www.linkedin.com/in/kolgarn/">LinkedIn</Lnk>). MIT licence.
      </p>
    </footer>
  );
}
