import type { ComponentChildren } from "preact";
import { day } from "../domain/format";
import { useReport } from "./context";

/** A footer link: always to a fixed lockrot address, never to anything from the document. */
function Lnk({ href, children }: { href: string; children: ComponentChildren }) {
  return (
    <a className="lnk" href={href} target="_blank" rel="noopener noreferrer">
      {children}
    </a>
  );
}

/**
 * The colophon: who made the instrument, not who was audited (legacy report.html:94-120). A report
 * is usually read by someone who did not run it, so the page says how to get the same page for
 * their own lock instead of leaving them to work it out from a link to the documentation.
 */
export function Footer() {
  const { model } = useReport();
  const version = model.report.tool.version ?? "—";

  return (
    <footer className="colophon">
      <p>
        Generated by lockrot <span className="mono">{version}</span> on{" "}
        <span className="mono">{day(model.report.generatedAt)}</span>. Everything it shows is inside this
        file; nothing in it loads from the network.
      </p>
      <p className="cta">
        Run it on your own <span className="mono">composer.lock</span>:{" "}
        <code>composer require --dev somework/lockrot</code>, then{" "}
        <code>composer lockrot --format=html &gt; report.html</code>. No Composer plugin wanted? The{" "}
        <Lnk href="https://lockrot.dev/lockrot.phar">PHAR</Lnk> needs nothing installed.
      </p>
      <p>
        <Lnk href="https://github.com/somework/lockrot">Source</Lnk> &middot;{" "}
        <Lnk href="https://packagist.org/packages/somework/lockrot">somework/lockrot</Lnk> &middot;{" "}
        <Lnk href="https://lockrot.dev/">Documentation</Lnk> &middot;{" "}
        <Lnk href="https://github.com/somework/lockrot/issues">Report a wrong verdict</Lnk>
      </p>
      <p>
        Written by <Lnk href="https://github.com/somework">Igor Pinchuk</Lnk> (
        <Lnk href="https://www.linkedin.com/in/kolgarn/">LinkedIn</Lnk>). MIT licence.
      </p>
    </footer>
  );
}
